name: Go Verify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/tinygo-org/tinygo-dev

    steps:
    - name: Checkout Playground Go
      uses: actions/checkout@v3

    - name: Build
      run: |
        git status
        make build buildtiny

    - name: Tests
      run: |
        make test testtiny
